Перемещен slice и api в директорию компонента Audio, трансформирван useSelector в connect
okjel/social-network pull request #31
Opened 2021-01-17 10:10 UTC by okjel

2021-01-17 15:19 UTC, PavelBalyakin commented
Думал, что вопрос вынесения стора и сервисов поднимем позже. Я за, давай попробуем.

2021-01-17 15:32 UTC, PavelBalyakin requested changes
Думал, что вопрос вынесения стора и сервисов поднимем позже. Я за, давай попробуем.

2021-01-17 15:32 UTC, PavelBalyakin commented on src/components/Audio/Audio.tsx
> +import { connect, useDispatch } from 'react-redux';
Можешь объяснить или привести доводы почему лучше использовать хок коннект вместо хуков?
Мне ментор говорил, что обычно предпочтительнее использовать коннект, так как компонент проще переиспользовать. С другой стороны, может и не нужно его переиспользовать.
Интересно услышать твое соображение, может быть что-то новое от тебя узнаю. ;)

2021-01-17 16:39 UTC, Flotskey commented on src/components/Audio/Audio.tsx
> +import { connect, useDispatch } from 'react-redux';
Я вот нашёл такой довод, что useSelector в плане производительности чуть хуже (могут быть лишние рендеры). Тут в видосе объясняют разницу connect vs useSelector - https://www.youtube.com/watch?v=C3dhHcAElMM (там хорошо есть прописанные человеком субтитры, так что их можно включить)

2021-01-17 16:40 UTC, Flotskey commented on src/components/Audio/Audio.tsx
> +import { connect, useDispatch } from 'react-redux';
но если на производительность не влияет, то смысла думаю немного менять на коннект

2021-01-17 21:12 UTC, Egor1408 commented on src/components/Audio/Audio.tsx
> +import { connect, useDispatch } from 'react-redux';
вообще я тоже читал, вот цитата: 
- в отличие от connect, хук useSelector не предотвращает повторный ререндер компонента, когда перерисовывается родитель, даже если пропы не изменились. Поэтому для оптимизации стоит использовать React.memo();

2021-01-18 04:45 UTC, PavelBalyakin commented on src/components/Audio/Audio.tsx
> +import { connect, useDispatch } from 'react-redux';
Видео забавное и не вижу проблем для того, чтобы использовать функции мемоизации, ок, может Артем что-то добавит.

2021-01-19 12:26 UTC, okjel commented on src/components/Audio/Audio.tsx
> +import { connect, useDispatch } from 'react-redux';
привычнее пропсы) 
также добавляется типизация входящих пропсов. (хотя нужно посмотреть бест практис по useSelector, может с типизации нет проблем у useSelector)
```
const Audio = ({
  isLoading,
  error,
  myPlaylists,
  allAudios,
  friends,
  myAudios,
  currentSearch,
}: AudioProps): JSX.Element => {
```
также планирую заменить useDispatch() на передачу thunk из slice через пропсы, 
по итогу через пропы передается все необходимое + типизируемое и без useSelector и без useDispatcher.

2021-01-19 13:40 UTC, PavelBalyakin commented on src/components/Audio/Audio.tsx
> +import { connect, useDispatch } from 'react-redux';
Ну, привычнее, так привычнее  - это тоже аргумент. Думаю, что о типизации позаботились, просто пока мы не научились ее использовать. И, возможно, что она удобнее. Так как, возможно, в твоем случае тебе придется типизировать несколько раз одни и те же сущности.

2021-01-19 13:40 UTC, PavelBalyakin approved these changes

2021-01-19 13:40 UTC, merged